### ISSUE TITLE
Differences in result of span pre and post 1.7 release

### ISSUE THREAD

**Issue by bmw** [hercules-team/augeas#466] opened 2017-05-12 22:00 UTC
I created this directory structure in `/home/bmw`:
```
$ ls -R
.:
augeas_lens  commands  default.conf

./augeas_lens:
httpd.au
```
The files are [httpd.aug](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/augeas_lens/httpd.aug), [default.conf](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/tests/testdata/debian_apache_2_4/multi_vhosts/apache2/sites-available/default.conf), and `commands` is:
```
transform Httpd incl /home/bmw/default.conf
load
span /files/home/bmw/default.conf/VirtualHost[2]
```
Running `augtool -f commands -I augeas_lens/ -L --span` from this directory produces different output depending on the Augeas version. Using Augeas 1.6, the output is:
```
$ augtool -f commands -I augeas_lens/ -L --span
/home/bmw/default.conf label=(216:227) value=(0:0) span=(215,414)
```
while using Augeas 1.7 the output is:
```
$ augtool -f commands -I augeas_lens/ -L --span
/home/bmw/default.conf label=(216:227) value=(0:0) span=(215,429)
```
This difference doesn't seem to be documented.

I tested this using the Ubuntu 17.04 Docker image for Augeas 1.6 and Fedora 24 Docker image for Augeas 1.7 so it's possible the difference is something other than just the Augeas version, but I've gotten reports of similar things from other developers in certbot/certbot#4624.

**Comment by domcleal** [comment] 2017-05-12 22:35
323c6451720355d98f20aac87a511f175acd845e is the commit changing the behaviour.

**Comment by lutter** [comment] 2017-09-08 22:53
Yes, that change is a consequence of the fix that @domcleal mentioned above. The previous value was simply incorrect.

My apologies, I should have noted that this change can lead to span values changing more clearly in the release notes. Since the corresponding bug in certbot is closed, is there anything that still needs to be done here ?

**Comment by bmw** [comment] 2017-09-13 17:40
If the current behavior is the desired one, I don't think anything else needs to be done here. We've worked around the problem in Certbot.

**Comment by lutter** [comment] 2017-09-14 00:01
Ok. Closing this, as it is indeed the intended behavior.

**Closed by lutter** 2017-09-14 00:01 UTC
Labels: library
