### ISSUE TITLE
CSV lens fails: Failed to compile comment

### ISSUE THREAD

**Issue by jasperla** [hercules-team/augeas#396] opened 2016-08-13 08:25 UTC
```
basalt:2070 augeas % augtool -b
Failed to initialize Augeas
error: Syntax error in lens definition
/usr/local/share/augeas/lenses/dist/csv.aug:30.0-31.43:Failed to compile comment
/usr/local/share/augeas/lenses/dist/csv.aug:31.16-.41:exception: del: the default value '#\n' does not match /\\^#[\t ]*\r?\n/
```

This is with Augeas 1.6.0 but it also shows up with Augeas 1.5.0.

**Comment by domcleal** [comment] 2016-08-15 07:35
Can you confirm if removing the `^` from the comment regex fixes the issue for you? The character's unnecessary and it looks like it's being escaped for you, which is probably why it's failing to match the default value.

**Comment by jasperla** [comment] 2016-08-15 07:38
I can confirm that indeed.

**Comment by domcleal** [comment] 2016-08-15 07:45
Thanks, fix merged.

**Closed by domcleal** 2016-08-15 07:45 UTC

**Comment by jasperla** [comment] 2016-08-15 10:30
Thanks for the quick fix!

**Comment by lutter** [comment] 2016-08-17 23:02
This seems to be caused by an annoying limitation in GNU regex: `^` (and `$`) shouldn't have a special meaning, but it seems it is impossible to turn that off if the `^` is at the beginning (the `$` is at the end) of a regular expression.

When the `del RE S` lens is typechecked, we simply see if `S` matches `RE`. I wonder if that check should be changed so that we try to match `xSx` with `xREx` or some variation thereof.

@jasperla did you encounter this on OpenBSD ? Does the implementation of `re_compile_pattern` come from its C library ? I am trying to understand why this doesn't happen on Fedora or Debian.

**Comment by jasperla** [comment] 2016-08-18 06:47
@lutter I did indeed encounter this on OpenBSD. However `re_compile_pattern` comes from `gnulib`. I think the closest BSD libc/POSIX equivalent would be [regcomp(3)](http://man.openbsd.org/OpenBSD-current/man3/regex.3)
